on:
  push:
    branches: [ main ]

jobs:
  publish-snapshot:
    runs-on: macos-latest
    if: github.event.repository.fork == false

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - run: |
          ./gradlew librarianPublishToSnapshots
        env:
          LIBRARIAN_SONATYPE_USERNAME: ${{ secrets.LIBRARIAN_SONATYPE_USERNAME }}
          LIBRARIAN_SONATYPE_PASSWORD: ${{ secrets.LIBRARIAN_SONATYPE_PASSWORD }}
