on:
  push:
    tags:
      - '*'

jobs:
  publish-release:
    runs-on: macos-latest
    if: github.event.repository.fork == false

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - run: |
          LIBRARIAN_RELEASE=true ./gradlew librarianPublishToMavenCentral
        env:
          LIBRARIAN_SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          LIBRARIAN_SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          LIBRARIAN_SIGNING_PRIVATE_KEY: ${{ secrets.SONATYPE_GPG_KEY }}
          LIBRARIAN_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.SONATYPE_GPG_KEY_KEY_PASSWORD }}
